import uk.ac.imperial.einst.Actor
import uk.ac.imperial.einst.Action

import uk.ac.imperial.einst.ipower.Obl
import uk.ac.imperial.einst.ipower.Pow

global org.apache.log4j.Logger logger

declare Pow
	@role( event )
end

query pow(Actor a, Action act)
	pow : Pow(actor == a, this.matches(act))
end

query allPows(Actor a)
	pow : Pow(actor == a)
end

query obl(Actor a)
	obl : Obl(actor == a)
end

rule "Mark satisfied Obligations"
	when
		$act : Action($a : actor)
		$obl : Obl(this.matches($act), actor == $a, done == false)
	then
		modify($obl) {
			setDone(true);
		}
end
